spring:
  cloud:
    gateway:
      routes:
        - id: cliente-route
          uri: lb://cliente-service
          predicates:
            - Path=/clientes/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

meu:
  test: TESTE
